[program:laravel-worker]
command=php /var/www/artisan queue:work redis --sleep=3 --tries=3
autostart=true
autorestart=true
stdout_logfile=/var/www/storage/logs/worker.log
stderr_logfile=/var/www/storage/logs/worker_error.log
