name: CI

on:
  push:
    branches:
      - main
      - dev-*

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - run: |
          cd my-app
          composer install
          php artisan test

      - run: |
          docker build -t ghcr.io/${{ github.repository }}:dev -f docker/php/Dockerfile .
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/${{ github.repository }}:dev